import json # AI-Generated by Claude
import os # AI-Generated by Claude
import pytest # AI-Generated by Claude
from setup_hooks import inject_hooks, HOOK_EVENTS # AI-Generated by Claude


def _settings_path(tmp_path):  # AI-Generated by Claude
    return str(tmp_path / ".claude" / "settings.json")  # AI-Generated by Claude


def _all_commands(data):  # AI-Generated by Claude
    """Collect all 'command' values from the hooks map."""  # AI-Generated by Claude
    cmds = []  # AI-Generated by Claude
    for event_hooks in data.get("hooks", {}).values():  # AI-Generated by Claude
        for matcher_group in event_hooks:  # AI-Generated by Claude
            for h in matcher_group.get("hooks", []):  # AI-Generated by Claude
                if "command" in h:  # AI-Generated by Claude
                    cmds.append(h["command"])  # AI-Generated by Claude
    return cmds  # AI-Generated by Claude


def test_inject_creates_settings_when_missing(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    assert os.path.exists(settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    assert "hooks" in data  # AI-Generated by Claude


def test_inject_adds_all_hook_events(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    assert set(data["hooks"].keys()) == set(HOOK_EVENTS)  # AI-Generated by Claude


def test_inject_is_idempotent(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    # Each event should have exactly one matcher group for our command
    for event in HOOK_EVENTS:  # AI-Generated by Claude
        assert len(data["hooks"][event]) == 1  # AI-Generated by Claude


def test_inject_preserves_existing_keys(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)  # AI-Generated by Claude
    with open(settings_file, "w") as f:  # AI-Generated by Claude
        json.dump({"customKey": "value"}, f)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    assert data["customKey"] == "value"  # AI-Generated by Claude


def test_inject_merges_without_removing_existing_hooks(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)  # AI-Generated by Claude
    existing = {"hooks": {"PreToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "command": "echo existing"}]}]}}  # AI-Generated by Claude
    with open(settings_file, "w") as f:  # AI-Generated by Claude
        json.dump(existing, f)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    # Both the existing hook and our new hook should be present
    all_cmds = _all_commands(data)  # AI-Generated by Claude
    assert any("hook_writer" in c for c in all_cmds)  # AI-Generated by Claude
    assert any("echo existing" in c for c in all_cmds)  # AI-Generated by Claude
