import sys, os # AI-Generated by Claude
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src")) # AI-Generated by Claude

import pytest # AI-Generated by Claude
from unittest.mock import MagicMock # AI-Generated by Claude
from PyQt6.QtCore import QPoint # AI-Generated by Claude
from bubble_overlay import BubbleOverlay # AI-Generated by Claude


def _make_pet(x=100, y=200, w=103, h=77): # AI-Generated by Claude
    pet = MagicMock() # AI-Generated by Claude
    pet.pos.return_value = QPoint(x, y) # AI-Generated by Claude
    pet.width.return_value = w # AI-Generated by Claude
    pet.height.return_value = h # AI-Generated by Claude
    return pet # AI-Generated by Claude


def test_initial_state_hidden(qapp): # AI-Generated by Claude
    pet = _make_pet() # AI-Generated by Claude
    overlay = BubbleOverlay(pet) # AI-Generated by Claude
    assert not overlay.isVisible() # AI-Generated by Claude


def test_reposition_centers_above_pet(qapp): # AI-Generated by Claude
    pet = _make_pet(x=100, y=200, w=103, h=77) # AI-Generated by Claude
    overlay = BubbleOverlay(pet) # AI-Generated by Claude
    overlay.reposition() # AI-Generated by Claude
    expected_x = 100 + (103 - BubbleOverlay.WIDTH) // 2 # AI-Generated by Claude
    expected_y = 200 - BubbleOverlay.HEIGHT - 8 # AI-Generated by Claude
    assert overlay.x() == expected_x # AI-Generated by Claude
    assert overlay.y() == expected_y # AI-Generated by Claude


def test_show_bubble_makes_visible(qapp): # AI-Generated by Claude
    overlay = BubbleOverlay(_make_pet()) # AI-Generated by Claude
    overlay.show_bubble() # AI-Generated by Claude
    assert overlay.isVisible() # AI-Generated by Claude
    overlay.hide_bubble() # AI-Generated by Claude


def test_hide_bubble_hides(qapp): # AI-Generated by Claude
    overlay = BubbleOverlay(_make_pet()) # AI-Generated by Claude
    overlay.show_bubble() # AI-Generated by Claude
    overlay.hide_bubble() # AI-Generated by Claude
    assert not overlay.isVisible() # AI-Generated by Claude
