import json # AI-Generated by Claude
import os # AI-Generated by Claude
import pytest # AI-Generated by Claude
from setup_hooks import inject_hooks, HOOK_EVENTS # AI-Generated by Claude


def _settings_path(tmp_path):  # AI-Generated by Claude
    return str(tmp_path / ".claude" / "settings.json")  # AI-Generated by Claude


def _hook_writer_cmd(scripts_dir):  # AI-Generated by Claude
    return f"python {os.path.join(scripts_dir, 'hook_writer.py')}"  # AI-Generated by Claude


def test_inject_creates_settings_when_missing(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    assert os.path.exists(settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    assert "hooks" in data  # AI-Generated by Claude


def test_inject_adds_all_hook_events(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    hook_types = {h["type"] for h in data["hooks"]}  # AI-Generated by Claude
    assert hook_types == set(HOOK_EVENTS)  # AI-Generated by Claude


def test_inject_is_idempotent(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    # No duplicate hooks
    types = [h["type"] for h in data["hooks"]]  # AI-Generated by Claude
    assert len(types) == len(set(types))  # AI-Generated by Claude


def test_inject_preserves_existing_keys(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)  # AI-Generated by Claude
    with open(settings_file, "w") as f:  # AI-Generated by Claude
        json.dump({"customKey": "value"}, f)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    assert data["customKey"] == "value"  # AI-Generated by Claude


def test_inject_merges_without_removing_existing_hooks(tmp_path):  # AI-Generated by Claude
    settings_file = _settings_path(tmp_path)  # AI-Generated by Claude
    os.makedirs(os.path.dirname(settings_file), exist_ok=True)  # AI-Generated by Claude
    existing = {"hooks": [{"type": "PreToolUse", "command": "echo existing"}]}  # AI-Generated by Claude
    with open(settings_file, "w") as f:  # AI-Generated by Claude
        json.dump(existing, f)  # AI-Generated by Claude
    inject_hooks(str(tmp_path), settings_file=settings_file)  # AI-Generated by Claude
    data = json.loads(open(settings_file).read())  # AI-Generated by Claude
    commands = [h["command"] for h in data["hooks"] if h["type"] == "PreToolUse"]  # AI-Generated by Claude
    # Our hook should be present
    assert any("hook_writer" in c for c in commands)  # AI-Generated by Claude
