import json
import os
import pytest
from hook_writer import determine_state, write_state, state_file_for_project


def test_pre_tool_read_maps_to_reading():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Read"}) == "reading"


def test_pre_tool_glob_maps_to_reading():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Glob"}) == "reading"


def test_pre_tool_grep_maps_to_reading():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Grep"}) == "reading"


def test_pre_tool_edit_maps_to_writing():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Edit"}) == "writing"


def test_pre_tool_write_maps_to_writing():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Write"}) == "writing"


def test_pre_tool_bash_maps_to_executing():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Bash"}) == "executing"


def test_pre_tool_agent_maps_to_thinking():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "Agent"}) == "thinking"


def test_pre_tool_taskcreate_maps_to_thinking():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "TaskCreate"}) == "thinking"


def test_pre_tool_taskupdate_maps_to_thinking():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "TaskUpdate"}) == "thinking"


def test_pre_tool_unknown_maps_to_thinking():
    assert determine_state({"hook_event_name": "PreToolUse", "tool_name": "SomeFutureTool"}) == "thinking"


def test_post_tool_maps_to_idle():
    assert determine_state({"hook_event_name": "PostToolUse", "tool_name": "Read"}) == "idle"


def test_notification_maps_to_waiting():
    assert determine_state({"hook_event_name": "Notification"}) == "waiting"


def test_stop_maps_to_idle():
    assert determine_state({"hook_event_name": "Stop"}) == "idle"


def test_empty_payload_maps_to_idle():
    assert determine_state({}) == "idle"


def test_write_state_creates_file(tmp_path, monkeypatch): # AI-Generated by Claude
    states_dir = str(tmp_path / "pet-states") # AI-Generated by Claude
    monkeypatch.setattr("hook_writer.STATES_DIR", states_dir) # AI-Generated by Claude
    write_state("reading", tool="Read", project="/fake/project") # AI-Generated by Claude
    target = state_file_for_project("/fake/project") # AI-Generated by Claude
    # state_file_for_project uses the real STATES_DIR, recalculate with tmp # AI-Generated by Claude
    files = list((tmp_path / "pet-states").glob("*.json")) # AI-Generated by Claude
    assert len(files) == 1 # AI-Generated by Claude
    data = json.loads(files[0].read_text()) # AI-Generated by Claude
    assert data["state"] == "reading" # AI-Generated by Claude
    assert data["tool"] == "Read" # AI-Generated by Claude
    assert data["project_name"] == "project" # AI-Generated by Claude
    assert "timestamp" in data # AI-Generated by Claude


def test_write_state_is_atomic(tmp_path, monkeypatch): # AI-Generated by Claude
    states_dir = str(tmp_path / "pet-states") # AI-Generated by Claude
    monkeypatch.setattr("hook_writer.STATES_DIR", states_dir) # AI-Generated by Claude
    write_state("idle", project="/fake/project") # AI-Generated by Claude
    tmp_files = list((tmp_path / "pet-states").glob("*.tmp")) # AI-Generated by Claude
    assert len(tmp_files) == 0 # AI-Generated by Claude


def test_state_file_for_project_deterministic(): # AI-Generated by Claude
    """Same path always produces the same hash.""" # AI-Generated by Claude
    a = state_file_for_project("/home/user/project") # AI-Generated by Claude
    b = state_file_for_project("/home/user/project") # AI-Generated by Claude
    assert a == b # AI-Generated by Claude


def test_state_file_for_project_different_paths(): # AI-Generated by Claude
    """Different paths produce different hashes.""" # AI-Generated by Claude
    a = state_file_for_project("/home/user/projectA") # AI-Generated by Claude
    b = state_file_for_project("/home/user/projectB") # AI-Generated by Claude
    assert a != b # AI-Generated by Claude


def test_write_state_no_project_uses_unknown(tmp_path, monkeypatch): # AI-Generated by Claude
    states_dir = str(tmp_path / "pet-states") # AI-Generated by Claude
    monkeypatch.setattr("hook_writer.STATES_DIR", states_dir) # AI-Generated by Claude
    write_state("idle", project="") # AI-Generated by Claude
    assert (tmp_path / "pet-states" / "_unknown.json").exists() # AI-Generated by Claude
