# assets/frames.py # AI-Generated by Claude
# All pixel frame data for the Claude Desktop Pet.
# Grid: 6 rows x 8 columns. Colors are "#RRGGBB" or "transparent".
# Eye positions (row=2): left=col2, right=col5.

T = "transparent" # AI-Generated by Claude
O = "#FF6432"  # Orange (body) # AI-Generated by Claude
W = "#FFFFFF"  # White (idle eye) # AI-Generated by Claude
P = "#AA44FF"  # Purple (thinking eye) # AI-Generated by Claude
Y = "#FFDD44"  # Yellow (reading/executing eye) # AI-Generated by Claude
G = "#44FF88"  # Green (writing eye) # AI-Generated by Claude
R = "#FF3344"  # Red (waiting eye) # AI-Generated by Claude
D = "#442211"  # Dim orange (unconfigured body) # AI-Generated by Claude
DE = "#553322"  # Dim eye (unconfigured) # AI-Generated by Claude


def _row0(c=O): return [T, T, c, c, c, c, T, T] # AI-Generated by Claude
def _row1(c=O): return [T, c, c, c, c, c, c, T] # AI-Generated by Claude
def _row3(c=O): return [c, c, c, c, c, c, c, c] # AI-Generated by Claude
def _row5(c=O): return [T, c, c, T, T, c, c, T] # AI-Generated by Claude


def _make_frame(eye_color, lc=2, rc=5, bar_cols=0, body=O): # AI-Generated by Claude
    """Build one 6x8 frame. lc/rc = left/right eye column (0-indexed)."""
    row2 = [body] * 8 # AI-Generated by Claude
    row2[lc] = eye_color # AI-Generated by Claude
    row2[rc] = eye_color # AI-Generated by Claude
    row4 = [body] * 8 # AI-Generated by Claude
    for i in range(1, 1 + bar_cols): # AI-Generated by Claude
        row4[i] = G # AI-Generated by Claude
    return [ # AI-Generated by Claude
        _row0(body), # AI-Generated by Claude
        _row1(body), # AI-Generated by Claude
        row2, # AI-Generated by Claude
        _row3(body), # AI-Generated by Claude
        row4, # AI-Generated by Claude
        _row5(body), # AI-Generated by Claude
    ]


def _make_wide_frame(eye_color, left_cols, right_cols, body=O): # AI-Generated by Claude
    """Wide eyes: multiple columns per eye."""
    row2 = [body] * 8 # AI-Generated by Claude
    for c in left_cols: # AI-Generated by Claude
        row2[c] = eye_color # AI-Generated by Claude
    for c in right_cols: # AI-Generated by Claude
        row2[c] = eye_color # AI-Generated by Claude
    return [ # AI-Generated by Claude
        _row0(body), # AI-Generated by Claude
        _row1(body), # AI-Generated by Claude
        row2, # AI-Generated by Claude
        _row3(body), # AI-Generated by Claude
        _row3(body), # AI-Generated by Claude
        _row5(body), # AI-Generated by Claude
    ]


FRAMES = { # AI-Generated by Claude
    # Static dim appearance - no animation
    "unconfigured": [ # AI-Generated by Claude
        _make_frame(DE, body=D), # AI-Generated by Claude
    ],

    # White eyes, slow blink cycle (4 frames)
    "idle": [ # AI-Generated by Claude
        _make_frame(W),        # f0: eyes open # AI-Generated by Claude
        _make_frame(W),        # f1: eyes open (hold) # AI-Generated by Claude
        _make_frame(O),        # f2: blink closed # AI-Generated by Claude
        _make_frame(W),        # f3: eyes reopen # AI-Generated by Claude
    ],

    # Purple eyes shifting left-center-right (4 frames)
    "thinking": [ # AI-Generated by Claude
        _make_frame(P, 2, 5),  # f0: center # AI-Generated by Claude
        _make_frame(P, 1, 4),  # f1: left # AI-Generated by Claude
        _make_frame(P, 2, 5),  # f2: center # AI-Generated by Claude
        _make_frame(P, 3, 6),  # f3: right # AI-Generated by Claude
    ],

    # Yellow eyes scanning left-center-right (4 frames)
    "reading": [ # AI-Generated by Claude
        _make_frame(Y, 2, 5),  # f0: center # AI-Generated by Claude
        _make_frame(Y, 1, 4),  # f1: look left # AI-Generated by Claude
        _make_frame(Y, 2, 5),  # f2: center # AI-Generated by Claude
        _make_frame(Y, 3, 6),  # f3: look right # AI-Generated by Claude
    ],

    # Green eyes + progress bar sweeping row 4 (4 frames)
    "writing": [ # AI-Generated by Claude
        _make_frame(G, bar_cols=0),  # f0: no bar # AI-Generated by Claude
        _make_frame(G, bar_cols=2),  # f1: 25% # AI-Generated by Claude
        _make_frame(G, bar_cols=4),  # f2: 50% # AI-Generated by Claude
        _make_frame(G, bar_cols=6),  # f3: 75% # AI-Generated by Claude
    ],

    # Wide yellow eyes alternating (4 frames, shake via window motion)
    "executing": [ # AI-Generated by Claude
        _make_wide_frame(Y, [1, 2], [4, 5]),  # f0: wide left # AI-Generated by Claude
        _make_wide_frame(Y, [2, 3], [5, 6]),  # f1: wide right # AI-Generated by Claude
        _make_wide_frame(Y, [1, 2], [4, 5]),  # f2: wide left # AI-Generated by Claude
        _make_wide_frame(Y, [2, 3], [5, 6]),  # f3: wide right # AI-Generated by Claude
    ],

    # Red eyes flashing on/off (2 frames)
    "waiting": [ # AI-Generated by Claude
        _make_frame(R, 2, 5),  # f0: red eyes on # AI-Generated by Claude
        _make_frame(O, 2, 5),  # f1: eyes off # AI-Generated by Claude
    ],
}

# Milliseconds between frame advances per state # AI-Generated by Claude
FRAME_INTERVALS = { # AI-Generated by Claude
    "unconfigured": 1000, # AI-Generated by Claude
    "idle":         600, # AI-Generated by Claude
    "thinking":     150, # AI-Generated by Claude
    "reading":      300, # AI-Generated by Claude
    "writing":      200, # AI-Generated by Claude
    "executing":    80, # AI-Generated by Claude
    "waiting":      400, # AI-Generated by Claude
}

# Window motion type per state (applied by pet.py) # AI-Generated by Claude
STATE_MOTION = { # AI-Generated by Claude
    "unconfigured": "none", # AI-Generated by Claude
    "idle":         "float", # AI-Generated by Claude
    "thinking":     "tremble", # AI-Generated by Claude
    "reading":      "none", # AI-Generated by Claude
    "writing":      "none", # AI-Generated by Claude
    "executing":    "shake", # AI-Generated by Claude
    "waiting":      "none", # AI-Generated by Claude
}
