import json # AI-Generated by Claude
import os # AI-Generated by Claude
import sys # AI-Generated by Claude
import datetime # AI-Generated by Claude

STATE_FILE = os.path.join(os.path.expanduser("~"), ".claude", "pet-state.json") # AI-Generated by Claude

_READING_TOOLS = {"Read", "Glob", "Grep"} # AI-Generated by Claude
_WRITING_TOOLS = {"Edit", "Write"} # AI-Generated by Claude
_THINKING_TOOLS = {"Agent", "TaskCreate", "TaskUpdate"} # AI-Generated by Claude


def determine_state(payload: dict) -> str: # AI-Generated by Claude
    event = payload.get("hook_event_name", "") # AI-Generated by Claude
    tool = payload.get("tool_name", "") # AI-Generated by Claude

    if event == "PreToolUse": # AI-Generated by Claude
        if tool in _READING_TOOLS: # AI-Generated by Claude
            return "reading" # AI-Generated by Claude
        if tool in _WRITING_TOOLS: # AI-Generated by Claude
            return "writing" # AI-Generated by Claude
        if tool == "Bash": # AI-Generated by Claude
            return "executing" # AI-Generated by Claude
        return "thinking" # AI-Generated by Claude

    if event == "PostToolUse": # AI-Generated by Claude
        return "idle" # AI-Generated by Claude

    if event in ("Notification", "PermissionRequest"): # AI-Generated by Claude
        return "waiting" # AI-Generated by Claude

    if event == "Stop": # AI-Generated by Claude
        return "idle" # AI-Generated by Claude

    return "idle" # AI-Generated by Claude


def write_state(state: str, tool: str = "", project: str = "") -> None: # AI-Generated by Claude
    data = { # AI-Generated by Claude
        "state": state, # AI-Generated by Claude
        "tool": tool, # AI-Generated by Claude
        "project": project, # AI-Generated by Claude
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(), # AI-Generated by Claude
    } # AI-Generated by Claude
    tmp_file = STATE_FILE + ".tmp" # AI-Generated by Claude
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True) # AI-Generated by Claude
    with open(tmp_file, "w", encoding="utf-8") as f: # AI-Generated by Claude
        json.dump(data, f) # AI-Generated by Claude
    os.replace(tmp_file, STATE_FILE) # AI-Generated by Claude


def main() -> None: # AI-Generated by Claude
    try: # AI-Generated by Claude
        raw = sys.stdin.read() # AI-Generated by Claude
        payload = json.loads(raw) if raw.strip() else {} # AI-Generated by Claude
    except Exception as e: # AI-Generated by Claude
        print(f"hook_writer: failed to parse stdin: {e}", file=sys.stderr) # AI-Generated by Claude
        payload = {} # AI-Generated by Claude

    try: # AI-Generated by Claude
        state = determine_state(payload) # AI-Generated by Claude
        tool = payload.get("tool_name", "") # AI-Generated by Claude
        project = payload.get("cwd", "") # AI-Generated by Claude
        write_state(state, tool=tool, project=project) # AI-Generated by Claude
    except Exception as e: # AI-Generated by Claude
        print(f"hook_writer: failed to write state: {e}", file=sys.stderr) # AI-Generated by Claude

    sys.exit(0) # AI-Generated by Claude


if __name__ == "__main__": # AI-Generated by Claude
    main() # AI-Generated by Claude
