"""Inject Claude Code hooks into a project's .claude/settings.json.""" # AI-Generated by Claude
import json # AI-Generated by Claude
import os # AI-Generated by Claude
import sys # AI-Generated by Claude

HOOK_EVENTS = ["PreToolUse", "PostToolUse", "Notification", "Stop"] # AI-Generated by Claude

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__)) # AI-Generated by Claude


def _hook_command(scripts_dir: str) -> str: # AI-Generated by Claude
    hook_script = os.path.join(scripts_dir, "hook_writer.py") # AI-Generated by Claude
    return f"python {hook_script}" # AI-Generated by Claude


def inject_hooks( # AI-Generated by Claude
    project_dir: str, # AI-Generated by Claude
    settings_file: str | None = None, # AI-Generated by Claude
    scripts_dir: str | None = None, # AI-Generated by Claude
) -> None: # AI-Generated by Claude
    if settings_file is None: # AI-Generated by Claude
        settings_file = os.path.join(project_dir, ".claude", "settings.json") # AI-Generated by Claude
    if scripts_dir is None: # AI-Generated by Claude
        scripts_dir = _SCRIPTS_DIR # AI-Generated by Claude

    os.makedirs(os.path.dirname(settings_file), exist_ok=True) # AI-Generated by Claude

    if os.path.exists(settings_file): # AI-Generated by Claude
        with open(settings_file, "r", encoding="utf-8") as f: # AI-Generated by Claude
            try: # AI-Generated by Claude
                data = json.load(f) # AI-Generated by Claude
            except json.JSONDecodeError: # AI-Generated by Claude
                data = {} # AI-Generated by Claude
    else: # AI-Generated by Claude
        data = {} # AI-Generated by Claude

    hooks: list = data.setdefault("hooks", []) # AI-Generated by Claude
    cmd = _hook_command(scripts_dir) # AI-Generated by Claude

    existing_types_with_our_cmd = { # AI-Generated by Claude
        h["type"] for h in hooks if h.get("command") == cmd # AI-Generated by Claude
    } # AI-Generated by Claude

    for event in HOOK_EVENTS: # AI-Generated by Claude
        if event not in existing_types_with_our_cmd: # AI-Generated by Claude
            hooks.append({"type": event, "command": cmd}) # AI-Generated by Claude

    tmp_file = settings_file + ".tmp" # AI-Generated by Claude
    with open(tmp_file, "w", encoding="utf-8") as f: # AI-Generated by Claude
        json.dump(data, f, indent=2) # AI-Generated by Claude
    os.replace(tmp_file, settings_file) # AI-Generated by Claude
    print(f"Hooks injected into {settings_file}") # AI-Generated by Claude


def remove_hooks( # AI-Generated by Claude
    project_dir: str, # AI-Generated by Claude
    settings_file: str | None = None, # AI-Generated by Claude
    scripts_dir: str | None = None, # AI-Generated by Claude
) -> None: # AI-Generated by Claude
    """Remove hook_writer hooks from the project's settings.json.""" # AI-Generated by Claude
    if settings_file is None: # AI-Generated by Claude
        settings_file = os.path.join(project_dir, ".claude", "settings.json") # AI-Generated by Claude
    if scripts_dir is None: # AI-Generated by Claude
        scripts_dir = _SCRIPTS_DIR # AI-Generated by Claude
    if not os.path.exists(settings_file): # AI-Generated by Claude
        return # AI-Generated by Claude

    with open(settings_file, "r", encoding="utf-8") as f: # AI-Generated by Claude
        try: # AI-Generated by Claude
            data = json.load(f) # AI-Generated by Claude
        except json.JSONDecodeError: # AI-Generated by Claude
            return # AI-Generated by Claude

    cmd = _hook_command(scripts_dir) # AI-Generated by Claude
    original = data.get("hooks", []) # AI-Generated by Claude
    data["hooks"] = [h for h in original if h.get("command") != cmd] # AI-Generated by Claude

    tmp_file = settings_file + ".tmp" # AI-Generated by Claude
    with open(tmp_file, "w", encoding="utf-8") as f: # AI-Generated by Claude
        json.dump(data, f, indent=2) # AI-Generated by Claude
    os.replace(tmp_file, settings_file) # AI-Generated by Claude
    print(f"Hooks removed from {settings_file}") # AI-Generated by Claude


def main() -> None: # AI-Generated by Claude
    project_dir = sys.argv[1] if len(sys.argv) > 1 else os.getcwd() # AI-Generated by Claude
    inject_hooks(project_dir) # AI-Generated by Claude


if __name__ == "__main__": # AI-Generated by Claude
    main() # AI-Generated by Claude
