import sys # AI-Generated by Claude
import os # AI-Generated by Claude
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "assets")) # AI-Generated by Claude

from PyQt6.QtCore import QObject, QTimer, pyqtSignal # AI-Generated by Claude


class PetAnimator(QObject): # AI-Generated by Claude
    frame_changed = pyqtSignal(list) # AI-Generated by Claude
    motion_changed = pyqtSignal(str) # AI-Generated by Claude

    def __init__(self, parent=None): # AI-Generated by Claude
        super().__init__(parent) # AI-Generated by Claude
        self._state = "unconfigured" # AI-Generated by Claude
        self._frame_index = 0 # AI-Generated by Claude
        self._timer = QTimer(self) # AI-Generated by Claude
        self._timer.timeout.connect(self._advance_frame) # AI-Generated by Claude
        # Skin data is loaded lazily or set via set_skin()
        self._skin_data = None

    def _ensure_skin_loaded(self) -> None:
        """Ensure skin data is loaded. Loads default skin if not set."""
        if self._skin_data is None:
            from skin_registry import SkinRegistry
            registry = SkinRegistry()
            self._skin_data = registry.get_skin("default")

    def set_skin(self, skin) -> None:
        """Set the skin data. Accepts SkinModule or raw module with FRAMES/FRAME_INTERVALS/STATE_MOTION."""
        self._skin_data = skin
        # Refresh current state with new skin data
        self._frame_index = 0
        self._timer.stop()
        frames = self._get_frames(self._state)
        if len(frames) > 1:
            self._timer.start(self._get_interval(self._state))
        self.frame_changed.emit(self.current_frame())
        self.motion_changed.emit(self._get_motion(self._state))

    def _get_frames(self, state: str) -> list:
        """Get frames for a state, handling both SkinModule and raw module."""
        if hasattr(self._skin_data, 'frames'):
            return self._skin_data.frames.get(state, [])
        return self._skin_data.FRAMES.get(state, [])

    def _get_interval(self, state: str) -> int:
        """Get frame interval for a state."""
        if hasattr(self._skin_data, 'frame_intervals'):
            return self._skin_data.frame_intervals.get(state, 600)
        return self._skin_data.FRAME_INTERVALS.get(state, 600)

    def _get_motion(self, state: str) -> str:
        """Get motion type for a state."""
        if hasattr(self._skin_data, 'state_motion'):
            return self._skin_data.state_motion.get(state, "none")
        return self._skin_data.STATE_MOTION.get(state, "none")

    def _has_state(self, state: str) -> bool:
        """Check if state exists in skin data."""
        if hasattr(self._skin_data, 'frames'):
            return state in self._skin_data.frames
        return state in self._skin_data.FRAMES

    @property
    def state(self) -> str: # AI-Generated by Claude
        return self._state # AI-Generated by Claude

    def set_state(self, state: str) -> None: # AI-Generated by Claude
        self._ensure_skin_loaded()
        if not self._has_state(state): # AI-Generated by Claude
            state = "unconfigured" # AI-Generated by Claude
        if state == self._state: # AI-Generated by Claude
            return # AI-Generated by Claude
        self._state = state # AI-Generated by Claude
        self._frame_index = 0 # AI-Generated by Claude
        self._timer.stop() # AI-Generated by Claude
        frames = self._get_frames(state)
        if len(frames) > 1: # AI-Generated by Claude
            self._timer.start(self._get_interval(state)) # AI-Generated by Claude
        self.frame_changed.emit(self.current_frame()) # AI-Generated by Claude
        self.motion_changed.emit(self._get_motion(state)) # AI-Generated by Claude

    def current_frame(self) -> list: # AI-Generated by Claude
        self._ensure_skin_loaded()
        frames = self._get_frames(self._state) or self._get_frames("unconfigured")
        return frames[self._frame_index % len(frames)] # AI-Generated by Claude

    def _advance_frame(self) -> None: # AI-Generated by Claude
        frames = self._get_frames(self._state) or self._get_frames("unconfigured")
        self._frame_index = (self._frame_index + 1) % len(frames) # AI-Generated by Claude
        self.frame_changed.emit(self.current_frame()) # AI-Generated by Claude

    def start(self) -> None: # AI-Generated by Claude
        self._ensure_skin_loaded()
        frames = self._get_frames(self._state) # AI-Generated by Claude
        if len(frames) > 1: # AI-Generated by Claude
            self._timer.start(self._get_interval(self._state)) # AI-Generated by Claude

    def stop(self) -> None: # AI-Generated by Claude
        self._timer.stop() # AI-Generated by Claude
