import sys # AI-Generated by Claude
import os # AI-Generated by Claude
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "assets")) # AI-Generated by Claude

from PyQt6.QtCore import QObject, QTimer, pyqtSignal # AI-Generated by Claude
from frames import FRAMES, FRAME_INTERVALS, STATE_MOTION # AI-Generated by Claude


class PetAnimator(QObject): # AI-Generated by Claude
    frame_changed = pyqtSignal(list) # AI-Generated by Claude
    motion_changed = pyqtSignal(str) # AI-Generated by Claude

    def __init__(self, parent=None): # AI-Generated by Claude
        super().__init__(parent) # AI-Generated by Claude
        self._state = "unconfigured" # AI-Generated by Claude
        self._frame_index = 0 # AI-Generated by Claude
        self._timer = QTimer(self) # AI-Generated by Claude
        self._timer.timeout.connect(self._advance_frame) # AI-Generated by Claude

    @property
    def state(self) -> str: # AI-Generated by Claude
        return self._state # AI-Generated by Claude

    def set_state(self, state: str) -> None: # AI-Generated by Claude
        if state not in FRAMES: # AI-Generated by Claude
            state = "unconfigured" # AI-Generated by Claude
        if state == self._state: # AI-Generated by Claude
            return # AI-Generated by Claude
        self._state = state # AI-Generated by Claude
        self._frame_index = 0 # AI-Generated by Claude
        self._timer.stop() # AI-Generated by Claude
        if len(FRAMES[state]) > 1: # AI-Generated by Claude
            self._timer.start(FRAME_INTERVALS.get(state, 600)) # AI-Generated by Claude
        self.frame_changed.emit(self.current_frame()) # AI-Generated by Claude
        self.motion_changed.emit(STATE_MOTION.get(state, "none")) # AI-Generated by Claude

    def current_frame(self) -> list: # AI-Generated by Claude
        frames = FRAMES.get(self._state, FRAMES["unconfigured"]) # AI-Generated by Claude
        return frames[self._frame_index % len(frames)] # AI-Generated by Claude

    def _advance_frame(self) -> None: # AI-Generated by Claude
        frames = FRAMES.get(self._state, FRAMES["unconfigured"]) # AI-Generated by Claude
        self._frame_index = (self._frame_index + 1) % len(frames) # AI-Generated by Claude
        self.frame_changed.emit(self.current_frame()) # AI-Generated by Claude

    def start(self) -> None: # AI-Generated by Claude
        frames = FRAMES.get(self._state, []) # AI-Generated by Claude
        if len(frames) > 1: # AI-Generated by Claude
            self._timer.start(FRAME_INTERVALS.get(self._state, 600)) # AI-Generated by Claude

    def stop(self) -> None: # AI-Generated by Claude
        self._timer.stop() # AI-Generated by Claude
