# src/bubble_overlay.py  # AI-Generated by Claude
from PyQt6.QtWidgets import QWidget  # AI-Generated by Claude
from PyQt6.QtGui import QPainter, QColor, QFont, QPolygon  # AI-Generated by Claude
from PyQt6.QtCore import Qt, QTimer, QPoint, QRect  # AI-Generated by Claude


class BubbleOverlay(QWidget):  # AI-Generated by Claude
    WIDTH = 50  # AI-Generated by Claude
    HEIGHT = 36  # AI-Generated by Claude

    def __init__(self, pet_window):  # AI-Generated by Claude
        super().__init__()  # AI-Generated by Claude
        self._pet = pet_window  # AI-Generated by Claude
        self._shake_direction = 1  # AI-Generated by Claude
        self._base_x = 0  # AI-Generated by Claude

        self.setWindowFlags(  # AI-Generated by Claude
            Qt.WindowType.FramelessWindowHint  # AI-Generated by Claude
            | Qt.WindowType.WindowStaysOnTopHint  # AI-Generated by Claude
        )  # macOS 上不使用 Tool
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)  # AI-Generated by Claude
        self.setFixedSize(self.WIDTH, self.HEIGHT)  # AI-Generated by Claude

        self._shake_timer = QTimer(self)  # AI-Generated by Claude
        self._shake_timer.setInterval(80)  # AI-Generated by Claude
        self._shake_timer.timeout.connect(self._apply_shake)  # AI-Generated by Claude

        self.hide()  # AI-Generated by Claude

    def paintEvent(self, event) -> None:  # AI-Generated by Claude
        painter = QPainter(self)  # AI-Generated by Claude
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)  # AI-Generated by Claude

        yellow = QColor("#F5C842")  # AI-Generated by Claude

        # Rounded rectangle (leave 2px margin on sides, 4px at top, 10px at bottom for triangle)
        rect = QRect(2, 2, self.WIDTH - 4, self.HEIGHT - 12)  # AI-Generated by Claude
        painter.setBrush(yellow)  # AI-Generated by Claude
        painter.setPen(Qt.PenStyle.NoPen)  # AI-Generated by Claude
        painter.drawRoundedRect(rect, 8, 8)  # AI-Generated by Claude

        # Downward triangle pointing at pet head
        mid_x = self.WIDTH // 2  # AI-Generated by Claude
        tri_top = rect.bottom()  # AI-Generated by Claude
        triangle = QPolygon([  # AI-Generated by Claude
            QPoint(mid_x - 6, tri_top),  # AI-Generated by Claude
            QPoint(mid_x + 6, tri_top),  # AI-Generated by Claude
            QPoint(mid_x, tri_top + 8),  # AI-Generated by Claude
        ])  # AI-Generated by Claude
        painter.drawPolygon(triangle)  # AI-Generated by Claude

        # Bell emoji
        painter.setPen(QColor("#333333"))  # AI-Generated by Claude
        font = QFont()  # AI-Generated by Claude
        font.setPixelSize(14)  # AI-Generated by Claude
        painter.setFont(font)  # AI-Generated by Claude
        painter.drawText(rect, Qt.AlignmentFlag.AlignCenter, "🔔")  # AI-Generated by Claude

        painter.end()  # AI-Generated by Claude

    def reposition(self) -> None:  # AI-Generated by Claude
        """Place bubble centered above the pet window."""  # AI-Generated by Claude
        pet_pos = self._pet.pos()  # AI-Generated by Claude
        x = pet_pos.x() + (self._pet.width() - self.WIDTH) // 2  # AI-Generated by Claude
        y = pet_pos.y() - self.HEIGHT - 8  # AI-Generated by Claude
        self._base_x = x  # AI-Generated by Claude
        self.move(x, y)  # AI-Generated by Claude

    def show_bubble(self) -> None:  # AI-Generated by Claude
        """Show the overlay, reposition it above the pet, and start the shake animation."""  # AI-Generated by Claude
        self.reposition()  # AI-Generated by Claude
        self.show()  # AI-Generated by Claude
        self._shake_timer.start()  # AI-Generated by Claude

    def hide_bubble(self) -> None:  # AI-Generated by Claude
        """Stop the shake animation and hide the overlay."""  # AI-Generated by Claude
        self._shake_timer.stop()  # AI-Generated by Claude
        self.hide()  # AI-Generated by Claude

    def _apply_shake(self) -> None:  # AI-Generated by Claude
        self._shake_direction *= -1  # AI-Generated by Claude
        self.move(self._base_x + self._shake_direction * 3, self.y())  # AI-Generated by Claude
