# src/bubble_overlay.py  # AI-Generated by Claude
from PyQt6.QtWidgets import QWidget  # AI-Generated by Claude
from PyQt6.QtCore import Qt, QTimer  # AI-Generated by Claude


class BubbleOverlay(QWidget):  # AI-Generated by Claude
    WIDTH = 50  # AI-Generated by Claude
    HEIGHT = 34  # AI-Generated by Claude

    def __init__(self, pet_window):  # AI-Generated by Claude
        super().__init__()  # AI-Generated by Claude
        self._pet = pet_window  # AI-Generated by Claude
        self._shake_direction = 1  # AI-Generated by Claude
        self._base_x = 0  # AI-Generated by Claude

        self.setWindowFlags(  # AI-Generated by Claude
            Qt.WindowType.FramelessWindowHint  # AI-Generated by Claude
            | Qt.WindowType.WindowStaysOnTopHint  # AI-Generated by Claude
            | Qt.WindowType.Tool  # AI-Generated by Claude
        )  # AI-Generated by Claude
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)  # AI-Generated by Claude
        self.setFixedSize(self.WIDTH, self.HEIGHT)  # AI-Generated by Claude

        self._shake_timer = QTimer(self)  # AI-Generated by Claude
        self._shake_timer.setInterval(80)  # AI-Generated by Claude
        self._shake_timer.timeout.connect(self._apply_shake)  # AI-Generated by Claude

        self.hide()  # AI-Generated by Claude

    def reposition(self) -> None:  # AI-Generated by Claude
        """Place bubble centered above the pet window."""  # AI-Generated by Claude
        pet_pos = self._pet.pos()  # AI-Generated by Claude
        x = pet_pos.x() + (self._pet.width() - self.WIDTH) // 2  # AI-Generated by Claude
        y = pet_pos.y() - self.HEIGHT - 8  # AI-Generated by Claude
        self._base_x = x  # AI-Generated by Claude
        self.move(x, y)  # AI-Generated by Claude

    def show_bubble(self) -> None:  # AI-Generated by Claude
        self.reposition()  # AI-Generated by Claude
        self.show()  # AI-Generated by Claude
        self._shake_timer.start()  # AI-Generated by Claude

    def hide_bubble(self) -> None:  # AI-Generated by Claude
        self._shake_timer.stop()  # AI-Generated by Claude
        self.hide()  # AI-Generated by Claude

    def _apply_shake(self) -> None:  # AI-Generated by Claude
        self._shake_direction *= -1  # AI-Generated by Claude
        self.move(self._base_x + self._shake_direction * 3, self.y())  # AI-Generated by Claude
