"""Cross-platform OS notification via plyer, with silent fallback.""" # AI-Generated by Claude


def notify(title: str, message: str, app_name: str = "Claude Desktop Pet") -> None: # AI-Generated by Claude
    """Send an OS notification. Silently ignores errors if plyer is unavailable.""" # AI-Generated by Claude
    try: # AI-Generated by Claude
        from plyer import notification # AI-Generated by Claude
        notification.notify( # AI-Generated by Claude
            title=title, # AI-Generated by Claude
            message=message, # AI-Generated by Claude
            app_name=app_name, # AI-Generated by Claude
            timeout=5, # AI-Generated by Claude
        ) # AI-Generated by Claude
    except Exception: # AI-Generated by Claude
        pass # AI-Generated by Claude
