import sys # AI-Generated by Claude
import json # AI-Generated by Claude
import os # AI-Generated by Claude
import time # AI-Generated by Claude
import math # AI-Generated by Claude
import random # AI-Generated by Claude
import argparse # AI-Generated by Claude
from pathlib import Path # AI-Generated by Claude

# Extend path so sibling packages resolve
_HERE = os.path.dirname(os.path.abspath(__file__)) # AI-Generated by Claude
sys.path.insert(0, _HERE) # AI-Generated by Claude
sys.path.insert(0, os.path.join(_HERE, "..", "scripts")) # AI-Generated by Claude
sys.path.insert(0, os.path.join(_HERE, "..", "assets")) # AI-Generated by Claude

from PyQt6.QtWidgets import QApplication, QWidget, QMenu, QFileDialog # AI-Generated by Claude
from PyQt6.QtCore import Qt, QTimer, QPoint, pyqtSlot # AI-Generated by Claude
from PyQt6.QtGui import QPainter # AI-Generated by Claude

from renderer import PetRenderer # AI-Generated by Claude
from animator import PetAnimator # AI-Generated by Claude
from notifier import notify # AI-Generated by Claude
from bubble_overlay import BubbleOverlay  # AI-Generated by Claude

STATE_FILE = Path.home() / ".claude" / "pet-state.json" # AI-Generated by Claude
CONFIG_FILE = Path.home() / ".claude" / "pet-config.json" # AI-Generated by Claude
STALE_THRESHOLD = 30  # seconds before forcing idle # AI-Generated by Claude


class PetWindow(QWidget): # AI-Generated by Claude
    def __init__(self, project: str = None): # AI-Generated by Claude
        super().__init__() # AI-Generated by Claude
        self._renderer = PetRenderer() # AI-Generated by Claude
        self._animator = PetAnimator(self) # AI-Generated by Claude
        self._drag_pos: QPoint | None = None # AI-Generated by Claude
        self._drag_moved = False # AI-Generated by Claude
        self._last_timestamp = "" # AI-Generated by Claude
        self._last_update_time = time.time() # AI-Generated by Claude
        self._project: str | None = None # AI-Generated by Claude
        self._motion_type = "none" # AI-Generated by Claude
        self._motion_step = 0 # AI-Generated by Claude
        self._base_pos: QPoint | None = None # AI-Generated by Claude

        self._setup_window() # AI-Generated by Claude
        self._animator.frame_changed.connect(self.update) # AI-Generated by Claude
        self._animator.motion_changed.connect(self._on_motion_changed) # AI-Generated by Claude

        self._poll_timer = QTimer(self) # AI-Generated by Claude
        self._poll_timer.timeout.connect(self._poll_state) # AI-Generated by Claude
        self._poll_timer.start(500) # AI-Generated by Claude

        self._motion_timer = QTimer(self) # AI-Generated by Claude
        self._motion_timer.timeout.connect(self._apply_motion) # AI-Generated by Claude

        if project: # AI-Generated by Claude
            self._configure_project(project) # AI-Generated by Claude
        else: # AI-Generated by Claude
            self._load_config() # AI-Generated by Claude

        self._animator.start() # AI-Generated by Claude
        self._bubble = BubbleOverlay(self)  # AI-Generated by Claude

    # ── Window setup ─────────────────────────────────────────────────────────

    def _setup_window(self) -> None: # AI-Generated by Claude
        self.setWindowFlags( # AI-Generated by Claude
            Qt.WindowType.FramelessWindowHint # AI-Generated by Claude
            | Qt.WindowType.WindowStaysOnTopHint # AI-Generated by Claude
            | Qt.WindowType.Tool # AI-Generated by Claude
        ) # AI-Generated by Claude
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground) # AI-Generated by Claude
        self.setFixedSize(PetRenderer.widget_width(), PetRenderer.widget_height()) # AI-Generated by Claude
        screen = QApplication.primaryScreen().geometry() # AI-Generated by Claude
        x = screen.width() - PetRenderer.widget_width() - 20 # AI-Generated by Claude
        y = screen.height() - PetRenderer.widget_height() - 60 # AI-Generated by Claude
        self.move(x, y) # AI-Generated by Claude
        self._base_pos = QPoint(x, y) # AI-Generated by Claude

    # ── Config / project ─────────────────────────────────────────────────────

    def _load_config(self) -> None: # AI-Generated by Claude
        if CONFIG_FILE.exists(): # AI-Generated by Claude
            try: # AI-Generated by Claude
                cfg = json.loads(CONFIG_FILE.read_text(encoding="utf-8")) # AI-Generated by Claude
                project = cfg.get("project") # AI-Generated by Claude
                if project and Path(project).exists(): # AI-Generated by Claude
                    self._project = project # AI-Generated by Claude
                    self._animator.set_state("idle") # AI-Generated by Claude
                    return # AI-Generated by Claude
            except Exception: # AI-Generated by Claude
                pass # AI-Generated by Claude
        self._project = None # AI-Generated by Claude
        self._animator.set_state("unconfigured") # AI-Generated by Claude

    def _configure_project(self, project_dir: str) -> None: # AI-Generated by Claude
        from setup_hooks import inject_hooks # AI-Generated by Claude
        scripts_dir = os.path.abspath(os.path.join(_HERE, "..", "scripts")) # AI-Generated by Claude
        inject_hooks(project_dir, scripts_dir=scripts_dir) # AI-Generated by Claude
        CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True) # AI-Generated by Claude
        CONFIG_FILE.write_text( # AI-Generated by Claude
            json.dumps({"project": project_dir}, ensure_ascii=False), # AI-Generated by Claude
            encoding="utf-8", # AI-Generated by Claude
        ) # AI-Generated by Claude
        self._project = project_dir # AI-Generated by Claude
        self._animator.set_state("idle") # AI-Generated by Claude

    def _remove_hooks(self) -> None: # AI-Generated by Claude
        if not self._project: # AI-Generated by Claude
            return # AI-Generated by Claude
        from setup_hooks import remove_hooks # AI-Generated by Claude
        scripts_dir = os.path.abspath(os.path.join(_HERE, "..", "scripts")) # AI-Generated by Claude
        remove_hooks(self._project, scripts_dir=scripts_dir) # AI-Generated by Claude
        self._project = None # AI-Generated by Claude
        CONFIG_FILE.unlink(missing_ok=True) # AI-Generated by Claude
        self._animator.set_state("unconfigured") # AI-Generated by Claude

    # ── Painting ─────────────────────────────────────────────────────────────

    def paintEvent(self, event): # AI-Generated by Claude
        painter = QPainter(self) # AI-Generated by Claude
        painter.setRenderHint(QPainter.RenderHint.Antialiasing, False) # AI-Generated by Claude
        self._renderer.render(painter, self._animator.current_frame()) # AI-Generated by Claude
        painter.end() # AI-Generated by Claude

    # ── Mouse interaction ─────────────────────────────────────────────────────

    def mousePressEvent(self, event): # AI-Generated by Claude
        if event.button() == Qt.MouseButton.LeftButton: # AI-Generated by Claude
            self._drag_pos = event.globalPosition().toPoint() - self.frameGeometry().topLeft() # AI-Generated by Claude
            self._drag_moved = False # AI-Generated by Claude

    def mouseMoveEvent(self, event): # AI-Generated by Claude
        if self._drag_pos and event.buttons() == Qt.MouseButton.LeftButton: # AI-Generated by Claude
            delta = event.globalPosition().toPoint() - self.frameGeometry().topLeft() - self._drag_pos # AI-Generated by Claude
            if delta.manhattanLength() > 3: # AI-Generated by Claude
                self._drag_moved = True # AI-Generated by Claude
            new_pos = event.globalPosition().toPoint() - self._drag_pos # AI-Generated by Claude
            self.move(new_pos) # AI-Generated by Claude
            self._base_pos = new_pos # AI-Generated by Claude
            self._bubble.reposition()  # AI-Generated by Claude

    def mouseReleaseEvent(self, event): # AI-Generated by Claude
        if event.button() == Qt.MouseButton.LeftButton: # AI-Generated by Claude
            if not self._drag_moved and self._animator.state == "unconfigured": # AI-Generated by Claude
                self._show_config_dialog() # AI-Generated by Claude
            self._drag_pos = None # AI-Generated by Claude
            self._drag_moved = False # AI-Generated by Claude

    def contextMenuEvent(self, event): # AI-Generated by Claude
        menu = QMenu(self) # AI-Generated by Claude
        project_name = Path(self._project).name if self._project else "未配置" # AI-Generated by Claude
        info = menu.addAction(f"📁 {project_name}") # AI-Generated by Claude
        info.setEnabled(False) # AI-Generated by Claude
        menu.addSeparator() # AI-Generated by Claude
        menu.addAction("切换项目…").triggered.connect(self._show_config_dialog) # AI-Generated by Claude
        menu.addAction("移除当前项目 Hooks").triggered.connect(self._remove_hooks) # AI-Generated by Claude
        menu.addSeparator() # AI-Generated by Claude
        menu.addAction("退出").triggered.connect(QApplication.quit) # AI-Generated by Claude
        menu.exec(event.globalPos()) # AI-Generated by Claude

    def _show_config_dialog(self) -> None: # AI-Generated by Claude
        folder = QFileDialog.getExistingDirectory(self, "选择项目文件夹") # AI-Generated by Claude
        if folder: # AI-Generated by Claude
            self._configure_project(folder) # AI-Generated by Claude

    # ── State polling ─────────────────────────────────────────────────────────

    @pyqtSlot()
    def _poll_state(self) -> None: # AI-Generated by Claude
        if not STATE_FILE.exists(): # AI-Generated by Claude
            return # AI-Generated by Claude
        try: # AI-Generated by Claude
            data = json.loads(STATE_FILE.read_text(encoding="utf-8")) # AI-Generated by Claude
            ts = data.get("timestamp", "") # AI-Generated by Claude
            state = data.get("state", "idle") # AI-Generated by Claude

            if ts != self._last_timestamp:  # AI-Generated by Claude
                self._last_timestamp = ts  # AI-Generated by Claude
                self._last_update_time = time.time()  # AI-Generated by Claude
                prev_state = self._animator.state  # AI-Generated by Claude
                if state == "waiting" and prev_state != "waiting":  # AI-Generated by Claude
                    notify("Claude Desktop Pet", "Claude 需要你的确认 🔔")  # AI-Generated by Claude
                    self._bubble.show_bubble()  # AI-Generated by Claude
                elif state != "waiting" and prev_state == "waiting":  # AI-Generated by Claude
                    self._bubble.hide_bubble()  # AI-Generated by Claude
                self._animator.set_state(state)  # AI-Generated by Claude
            else:  # AI-Generated by Claude
                elapsed = time.time() - self._last_update_time  # AI-Generated by Claude
                if elapsed > STALE_THRESHOLD:  # AI-Generated by Claude
                    if self._animator.state not in ("idle", "unconfigured"):  # AI-Generated by Claude
                        if self._animator.state == "waiting":  # AI-Generated by Claude
                            self._bubble.hide_bubble()  # AI-Generated by Claude
                        self._animator.set_state("idle")  # AI-Generated by Claude
        except Exception: # AI-Generated by Claude
            pass # AI-Generated by Claude

    # ── Window motion ─────────────────────────────────────────────────────────

    @pyqtSlot(str)
    def _on_motion_changed(self, motion_type: str) -> None: # AI-Generated by Claude
        self._motion_type = motion_type # AI-Generated by Claude
        self._motion_step = 0 # AI-Generated by Claude
        if motion_type != "none": # AI-Generated by Claude
            self._motion_timer.start(50) # AI-Generated by Claude
        else: # AI-Generated by Claude
            self._motion_timer.stop() # AI-Generated by Claude
            if self._base_pos: # AI-Generated by Claude
                self.move(self._base_pos) # AI-Generated by Claude

    @pyqtSlot()
    def _apply_motion(self) -> None: # AI-Generated by Claude
        if not self._base_pos: # AI-Generated by Claude
            return # AI-Generated by Claude
        self._motion_step += 1 # AI-Generated by Claude
        bx, by = self._base_pos.x(), self._base_pos.y() # AI-Generated by Claude
        if self._motion_type == "float": # AI-Generated by Claude
            offset_y = int(3 * math.sin(self._motion_step * 0.15)) # AI-Generated by Claude
            self.move(bx, by + offset_y) # AI-Generated by Claude
        elif self._motion_type == "shake": # AI-Generated by Claude
            self.move(bx + random.randint(-2, 2), by + random.randint(-2, 2)) # AI-Generated by Claude
        elif self._motion_type == "tremble": # AI-Generated by Claude
            self.move(bx + random.randint(-1, 1), by + random.randint(-1, 1)) # AI-Generated by Claude
        self._bubble.reposition()  # AI-Generated by Claude


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None: # AI-Generated by Claude
    parser = argparse.ArgumentParser(description="Claude Desktop Pet") # AI-Generated by Claude
    parser.add_argument("--project", default=None, help="Project dir to monitor immediately") # AI-Generated by Claude
    args = parser.parse_args() # AI-Generated by Claude

    app = QApplication(sys.argv) # AI-Generated by Claude
    app.setQuitOnLastWindowClosed(False) # AI-Generated by Claude

    window = PetWindow(project=args.project) # AI-Generated by Claude
    window.show() # AI-Generated by Claude

    sys.exit(app.exec()) # AI-Generated by Claude


if __name__ == "__main__": # AI-Generated by Claude
    main() # AI-Generated by Claude
