import sys # AI-Generated by Claude
import json # AI-Generated by Claude
import os # AI-Generated by Claude
import platform # AI-Generated by Claude
import time # AI-Generated by Claude
import math # AI-Generated by Claude
import random # AI-Generated by Claude
import argparse # AI-Generated by Claude
from pathlib import Path # AI-Generated by Claude

# Extend path so sibling packages resolve
_HERE = os.path.dirname(os.path.abspath(__file__)) # AI-Generated by Claude
sys.path.insert(0, _HERE) # AI-Generated by Claude
sys.path.insert(0, os.path.join(_HERE, "..", "scripts")) # AI-Generated by Claude
sys.path.insert(0, os.path.join(_HERE, "..", "assets")) # AI-Generated by Claude

from PyQt6.QtWidgets import QApplication, QWidget, QMenu, QFileDialog, QToolTip # AI-Generated by Claude
from PyQt6.QtCore import Qt, QTimer, QPoint, pyqtSlot # AI-Generated by Claude
from PyQt6.QtGui import QPainter # AI-Generated by Claude

from renderer import PetRenderer # AI-Generated by Claude
from animator import PetAnimator # AI-Generated by Claude
from notifier import notify # AI-Generated by Claude
from bubble_overlay import BubbleOverlay  # AI-Generated by Claude
from skin_registry import SkinRegistry  # AI-Generated by Claude

import datetime as _dt # AI-Generated by Claude

STATES_DIR = Path.home() / ".claude" / "pet-states" # AI-Generated by Claude
CONFIG_FILE = Path.home() / ".claude" / "pet-config.json" # AI-Generated by Claude
STALE_THRESHOLD = 30  # seconds before forcing idle # AI-Generated by Claude
MIN_STATE_DURATION = 2.0  # 每个状态至少持续 2 秒，避免状态一闪而过 # AI-Generated by Claude
CLEANUP_MAX_AGE_HOURS = 24  # 启动时清理超过此时长的状态文件 # AI-Generated by Claude

STATE_PRIORITY = { # AI-Generated by Claude
    "writing": 6, "executing": 5, "reading": 4, # AI-Generated by Claude
    "thinking": 3, "waiting": 2, "idle": 1, "unconfigured": 0, # AI-Generated by Claude
} # AI-Generated by Claude

STATE_EMOJI = { # AI-Generated by Claude
    "writing": "✏️", "executing": "⚡", "reading": "📖", # AI-Generated by Claude
    "thinking": "🤔", "waiting": "🔔", "idle": "💤", # AI-Generated by Claude
} # AI-Generated by Claude


class PetWindow(QWidget): # AI-Generated by Claude
    def __init__(self, project: str = None): # AI-Generated by Claude
        super().__init__() # AI-Generated by Claude
        # Initialize skin registry
        self._skin_registry = SkinRegistry()
        self._current_skin_id = "default"
        # Initialize with default skin dimensions (will be updated in _load_config)
        default_skin = self._skin_registry.get_skin("default")
        self._renderer = PetRenderer(rows=default_skin.rows, cols=default_skin.cols) # AI-Generated by Claude
        self._animator = PetAnimator(self) # AI-Generated by Claude
        self._animator.set_skin(default_skin) # Apply initial skin
        self._drag_pos: QPoint | None = None # AI-Generated by Claude
        self._drag_moved = False # AI-Generated by Claude
        self._state_change_time = time.time()  # 记录状态改变的时间 # AI-Generated by Claude
        self._project_states: dict[str, dict] = {}  # hash → state data # AI-Generated by Claude
        self._effective_state: str = "idle" # AI-Generated by Claude
        self._effective_project: str | None = None # AI-Generated by Claude
        self._motion_type = "none" # AI-Generated by Claude
        self._motion_step = 0 # AI-Generated by Claude
        self._base_pos: QPoint | None = None # AI-Generated by Claude

        self._setup_window() # AI-Generated by Claude
        self._animator.frame_changed.connect(self.update) # AI-Generated by Claude
        self._animator.motion_changed.connect(self._on_motion_changed) # AI-Generated by Claude

        self._poll_timer = QTimer(self) # AI-Generated by Claude
        self._poll_timer.timeout.connect(self._poll_state) # AI-Generated by Claude
        self._poll_timer.start(500) # AI-Generated by Claude

        self._motion_timer = QTimer(self) # AI-Generated by Claude
        self._motion_timer.timeout.connect(self._apply_motion) # AI-Generated by Claude

        self._load_config() # AI-Generated by Claude
        if project: # AI-Generated by Claude
            self._setup_project_hooks(project) # AI-Generated by Claude
        self._cleanup_stale_files() # AI-Generated by Claude
        self._animator.start() # AI-Generated by Claude
        self._bubble = BubbleOverlay(self)  # AI-Generated by Claude

    # ── Window setup ─────────────────────────────────────────────────────────

    def _setup_window(self) -> None: # AI-Generated by Claude
        self.setWindowFlags( # AI-Generated by Claude
            Qt.WindowType.FramelessWindowHint # AI-Generated by Claude
            | Qt.WindowType.WindowStaysOnTopHint # AI-Generated by Claude
        )  # macOS 上不使用 Tool，直接用普通窗口 + 置顶
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground) # AI-Generated by Claude
        self.setFixedSize(self._renderer.widget_width(), self._renderer.widget_height()) # AI-Generated by Claude
        screen = QApplication.primaryScreen().geometry() # AI-Generated by Claude
        x = screen.width() - self._renderer.widget_width() - 20 # AI-Generated by Claude
        # macOS: 右上角，留出菜单栏 + 气泡空间；Windows/Linux: 右下角
        if platform.system() == "Darwin":
            y = 50 + 25  # 菜单栏约 25px + 气泡空间 50px
        else:
            y = screen.height() - self._renderer.widget_height() - 60 # AI-Generated by Claude
        self.move(x, y) # AI-Generated by Claude
        self._base_pos = QPoint(x, y) # AI-Generated by Claude

    # ── Skin management ────────────────────────────────────────────────────────

    def _apply_skin(self, skin_id: str) -> None:
        """Apply a skin and update window size."""
        skin = self._skin_registry.get_skin(skin_id)
        self._current_skin_id = skin_id
        self._renderer.set_dimensions(skin.rows, skin.cols)
        self._animator.set_skin(skin)
        # Update window size
        self.setFixedSize(self._renderer.widget_width(), self._renderer.widget_height())
        # Reposition window to stay on screen
        screen = QApplication.primaryScreen().geometry()
        current_pos = self.pos()
        x = min(current_pos.x(), screen.width() - self._renderer.widget_width() - 20)
        y = min(current_pos.y(), screen.height() - self._renderer.widget_height() - 60)
        self.move(x, y)
        self._base_pos = QPoint(x, y)

    # ── Config / project ─────────────────────────────────────────────────────

    def _load_config(self) -> None: # AI-Generated by Claude
        if CONFIG_FILE.exists(): # AI-Generated by Claude
            try: # AI-Generated by Claude
                cfg = json.loads(CONFIG_FILE.read_text(encoding="utf-8")) # AI-Generated by Claude
                skin_id = cfg.get("skin", "default") # AI-Generated by Claude
                if skin_id != "default": # AI-Generated by Claude
                    self._apply_skin(skin_id) # AI-Generated by Claude
            except Exception: # AI-Generated by Claude
                pass # AI-Generated by Claude
        self._animator.set_state("idle") # AI-Generated by Claude

    def _save_config(self) -> None: # AI-Generated by Claude
        """Save current configuration to file.""" # AI-Generated by Claude
        cfg = {"skin": self._current_skin_id} # AI-Generated by Claude
        CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True) # AI-Generated by Claude
        CONFIG_FILE.write_text( # AI-Generated by Claude
            json.dumps(cfg, ensure_ascii=False), encoding="utf-8" # AI-Generated by Claude
        ) # AI-Generated by Claude

    def _cleanup_stale_files(self) -> None: # AI-Generated by Claude
        """启动时清理超过 24 小时的状态文件，防止无限增长。""" # AI-Generated by Claude
        if not STATES_DIR.exists(): # AI-Generated by Claude
            return # AI-Generated by Claude
        cutoff = _dt.datetime.now(_dt.timezone.utc) - _dt.timedelta(hours=CLEANUP_MAX_AGE_HOURS) # AI-Generated by Claude
        for f in STATES_DIR.glob("*.json"): # AI-Generated by Claude
            try: # AI-Generated by Claude
                data = json.loads(f.read_text(encoding="utf-8")) # AI-Generated by Claude
                ts = _dt.datetime.fromisoformat(data.get("timestamp", "")) # AI-Generated by Claude
                if ts < cutoff: # AI-Generated by Claude
                    f.unlink() # AI-Generated by Claude
            except Exception: # AI-Generated by Claude
                try: # AI-Generated by Claude
                    f.unlink() # AI-Generated by Claude
                except Exception: # AI-Generated by Claude
                    pass # AI-Generated by Claude

    def _setup_project_hooks(self, project_dir: str) -> None: # AI-Generated by Claude
        """为指定项目注入 hooks（不存储到配置）。""" # AI-Generated by Claude
        from setup_hooks import inject_hooks # AI-Generated by Claude
        scripts_dir = os.path.abspath(os.path.join(_HERE, "..", "scripts")) # AI-Generated by Claude
        inject_hooks(project_dir, scripts_dir=scripts_dir) # AI-Generated by Claude

    # ── Painting ─────────────────────────────────────────────────────────────

    def paintEvent(self, event): # AI-Generated by Claude
        painter = QPainter(self) # AI-Generated by Claude
        painter.setRenderHint(QPainter.RenderHint.Antialiasing, False) # AI-Generated by Claude
        self._renderer.render(painter, self._animator.current_frame()) # AI-Generated by Claude
        painter.end() # AI-Generated by Claude

    # ── Mouse interaction ─────────────────────────────────────────────────────

    def mousePressEvent(self, event): # AI-Generated by Claude
        if event.button() == Qt.MouseButton.LeftButton: # AI-Generated by Claude
            self._drag_pos = event.globalPosition().toPoint() - self.frameGeometry().topLeft() # AI-Generated by Claude
            self._drag_moved = False # AI-Generated by Claude

    def mouseMoveEvent(self, event): # AI-Generated by Claude
        if self._drag_pos and event.buttons() == Qt.MouseButton.LeftButton: # AI-Generated by Claude
            delta = event.globalPosition().toPoint() - self.frameGeometry().topLeft() - self._drag_pos # AI-Generated by Claude
            if delta.manhattanLength() > 3: # AI-Generated by Claude
                self._drag_moved = True # AI-Generated by Claude
            new_pos = event.globalPosition().toPoint() - self._drag_pos # AI-Generated by Claude
            self.move(new_pos) # AI-Generated by Claude
            self._base_pos = new_pos # AI-Generated by Claude
            self._bubble.reposition()  # AI-Generated by Claude

    def enterEvent(self, event) -> None: # AI-Generated by Claude
        tip = self.toolTip() # AI-Generated by Claude
        if tip: # AI-Generated by Claude
            from PyQt6.QtGui import QCursor # AI-Generated by Claude
            QToolTip.showText(QCursor.pos(), tip, self) # AI-Generated by Claude
        super().enterEvent(event) # AI-Generated by Claude

    def leaveEvent(self, event) -> None: # AI-Generated by Claude
        QToolTip.hideText() # AI-Generated by Claude
        super().leaveEvent(event) # AI-Generated by Claude

    def mouseReleaseEvent(self, event): # AI-Generated by Claude
        if event.button() == Qt.MouseButton.LeftButton: # AI-Generated by Claude
            if not self._drag_moved and not self._project_states: # AI-Generated by Claude
                self._show_setup_dialog() # AI-Generated by Claude
            self._drag_pos = None # AI-Generated by Claude
            self._drag_moved = False # AI-Generated by Claude

    def contextMenuEvent(self, event): # AI-Generated by Claude
        menu = QMenu(self) # AI-Generated by Claude

        # Header: project count # AI-Generated by Claude
        active_count = sum( # AI-Generated by Claude
            1 for p in self._project_states.values() if p.get("state", "idle") != "idle" # AI-Generated by Claude
        ) # AI-Generated by Claude
        total = len(self._project_states) # AI-Generated by Claude
        header = menu.addAction(f"📊 监听 {total} 个项目，{active_count} 个活跃") # AI-Generated by Claude
        header.setEnabled(False) # AI-Generated by Claude
        menu.addSeparator() # AI-Generated by Claude

        # Per-project status list # AI-Generated by Claude
        sorted_projects = sorted( # AI-Generated by Claude
            self._project_states.values(), # AI-Generated by Claude
            key=lambda p: STATE_PRIORITY.get(p.get("state", "idle"), 0), # AI-Generated by Claude
            reverse=True, # AI-Generated by Claude
        ) # AI-Generated by Claude
        for pdata in sorted_projects: # AI-Generated by Claude
            name = pdata.get("project_name") or "unknown" # AI-Generated by Claude
            state = pdata.get("state", "idle") # AI-Generated by Claude
            emoji = STATE_EMOJI.get(state, "❓") # AI-Generated by Claude
            action = menu.addAction(f"{emoji} {name} — {state}") # AI-Generated by Claude
            action.setEnabled(False) # AI-Generated by Claude
        if not self._project_states: # AI-Generated by Claude
            no_proj = menu.addAction("暂无活跃项目") # AI-Generated by Claude
            no_proj.setEnabled(False) # AI-Generated by Claude

        menu.addSeparator() # AI-Generated by Claude
        menu.addAction("配置新项目 Hooks…").triggered.connect(self._show_setup_dialog) # AI-Generated by Claude

        # Skin selection submenu
        menu.addSeparator() # AI-Generated by Claude
        skin_menu = menu.addMenu("切换形象")
        for skin in self._skin_registry.list_skins():
            action = skin_menu.addAction(skin.name)
            action.setCheckable(True)
            action.setChecked(skin.id == self._current_skin_id)
            action.triggered.connect(lambda checked, sid=skin.id: self._switch_skin(sid))

        # Import SVG skin
        menu.addAction("导入 SVG 皮肤…").triggered.connect(self._import_svg_skin) # AI-Generated by Claude

        menu.addSeparator() # AI-Generated by Claude
        menu.addAction("退出").triggered.connect(QApplication.quit) # AI-Generated by Claude
        menu.exec(event.globalPos()) # AI-Generated by Claude

    def _switch_skin(self, skin_id: str) -> None:
        """Switch to a different skin."""
        if skin_id == self._current_skin_id:
            return
        self._apply_skin(skin_id)
        self._save_config()

    def _import_svg_skin(self) -> None:
        """Import an SVG file as a new skin."""
        from PyQt6.QtWidgets import QInputDialog
        from pathlib import Path as PathLib
        import shutil

        # Select SVG file
        svg_path, _ = QFileDialog.getOpenFileName(
            self, "选择 SVG 文件", "", "SVG Files (*.svg)"
        )
        if not svg_path:
            return

        # Get skin name
        skin_name, ok = QInputDialog.getText(self, "皮肤名称", "请输入皮肤名称:")
        if not ok or not skin_name:
            return

        skin_id = skin_name.lower().replace(" ", "_")

        # Get eye positions (simple input for now)
        eye_pos, ok = QInputDialog.getText(
            self, "眼睛位置",
            "请输入眼睛位置 (格式: 左眼行,左眼列,右眼行,右眼列)\n例如: 2,2,2,5",
            text="2,2,2,5"
        )
        if not ok:
            return

        try:
            parts = [int(x.strip()) for x in eye_pos.split(",")]
            if len(parts) != 4:
                raise ValueError("Need 4 values")
            eye_left = [parts[0], parts[1]]
            eye_right = [parts[2], parts[3]]
        except ValueError:
            from PyQt6.QtWidgets import QMessageBox
            QMessageBox.warning(self, "错误", "眼睛位置格式错误")
            return

        # Create user skin directory
        user_skins_dir = PathLib.home() / ".claude" / "pet-skins"
        skin_dir = user_skins_dir / skin_id
        skin_dir.mkdir(parents=True, exist_ok=True)

        # Copy SVG file
        shutil.copy(svg_path, skin_dir / "base.svg")

        # Create config.json
        config = {
            "name": skin_name,
            "id": skin_id,
            "rows": 6,
            "cols": 8,
            "eye_left": eye_left,
            "eye_right": eye_right,
            "progress_row": 4
        }
        (skin_dir / "config.json").write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")

        # Reload registry and switch to new skin
        from skin_registry import SkinRegistry
        self._skin_registry = SkinRegistry()
        if skin_id in self._skin_registry.get_skin_ids():
            self._switch_skin(skin_id)
            from PyQt6.QtWidgets import QMessageBox
            QMessageBox.information(self, "成功", f"皮肤 '{skin_name}' 导入成功！")
        else:
            from PyQt6.QtWidgets import QMessageBox
            QMessageBox.warning(self, "错误", "皮肤导入失败")

    def _show_setup_dialog(self) -> None: # AI-Generated by Claude
        """弹出文件夹选择器，为选中的项目注入 hooks。""" # AI-Generated by Claude
        folder = QFileDialog.getExistingDirectory(self, "选择项目文件夹") # AI-Generated by Claude
        if folder: # AI-Generated by Claude
            self._setup_project_hooks(folder) # AI-Generated by Claude

    # ── State polling ─────────────────────────────────────────────────────────

    @pyqtSlot()
    def _poll_state(self) -> None: # AI-Generated by Claude
        now = time.time() # AI-Generated by Claude
        try: # AI-Generated by Claude
            if not STATES_DIR.exists(): # AI-Generated by Claude
                return # AI-Generated by Claude

            seen_hashes: set[str] = set() # AI-Generated by Claude
            for f in STATES_DIR.glob("*.json"): # AI-Generated by Claude
                h = f.stem # AI-Generated by Claude
                seen_hashes.add(h) # AI-Generated by Claude
                try: # AI-Generated by Claude
                    data = json.loads(f.read_text(encoding="utf-8")) # AI-Generated by Claude
                    ts = data.get("timestamp", "") # AI-Generated by Claude
                    existing = self._project_states.get(h) # AI-Generated by Claude
                    if not existing or existing.get("timestamp") != ts: # AI-Generated by Claude
                        data["last_seen"] = now # AI-Generated by Claude
                        self._project_states[h] = data # AI-Generated by Claude
                except (json.JSONDecodeError, OSError): # AI-Generated by Claude
                    continue # AI-Generated by Claude

            # 移除已不存在的文件对应的条目 # AI-Generated by Claude
            for h in list(self._project_states.keys()): # AI-Generated by Claude
                if h not in seen_hashes: # AI-Generated by Claude
                    del self._project_states[h] # AI-Generated by Claude

            # 超时的项目标记为 idle # AI-Generated by Claude
            for pdata in self._project_states.values(): # AI-Generated by Claude
                if now - pdata.get("last_seen", 0) > STALE_THRESHOLD: # AI-Generated by Claude
                    pdata["state"] = "idle" # AI-Generated by Claude

            self._resolve_effective_state(now) # AI-Generated by Claude
            self._update_tooltip() # AI-Generated by Claude
        except Exception: # AI-Generated by Claude
            pass # AI-Generated by Claude

    def _resolve_effective_state(self, now: float) -> None: # AI-Generated by Claude
        """从所有项目中选出优先级最高的状态驱动 animator。""" # AI-Generated by Claude
        best_state = "idle" # AI-Generated by Claude
        best_project = None # AI-Generated by Claude
        best_priority = -1 # AI-Generated by Claude

        for pdata in self._project_states.values(): # AI-Generated by Claude
            s = pdata.get("state", "idle") # AI-Generated by Claude
            p = STATE_PRIORITY.get(s, 0) # AI-Generated by Claude
            if p > best_priority: # AI-Generated by Claude
                best_priority = p # AI-Generated by Claude
                best_state = s # AI-Generated by Claude
                best_project = pdata.get("project_name") or pdata.get("project") # AI-Generated by Claude

        prev_state = self._effective_state # AI-Generated by Claude

        # MIN_STATE_DURATION 防抖：idle 降级需等待 # AI-Generated by Claude
        if best_state == "idle" and prev_state not in ("idle", "unconfigured"): # AI-Generated by Claude
            if now - self._state_change_time < MIN_STATE_DURATION: # AI-Generated by Claude
                return # AI-Generated by Claude

        # waiting 通知处理 # AI-Generated by Claude
        if best_state == "waiting" and prev_state != "waiting": # AI-Generated by Claude
            notify("Claude Desktop Pet", "Claude 需要你的确认 🔔") # AI-Generated by Claude
            self._bubble.show_bubble() # AI-Generated by Claude
        elif best_state != "waiting" and prev_state == "waiting": # AI-Generated by Claude
            self._bubble.hide_bubble() # AI-Generated by Claude

        if best_state != prev_state: # AI-Generated by Claude
            self._state_change_time = now # AI-Generated by Claude
            self._effective_state = best_state # AI-Generated by Claude
            self._effective_project = best_project # AI-Generated by Claude
            self._animator.set_state(best_state) # AI-Generated by Claude

    def _update_tooltip(self) -> None: # AI-Generated by Claude
        """更新悬停提示，显示所有项目状态。""" # AI-Generated by Claude
        lines = [] # AI-Generated by Claude
        for pdata in sorted( # AI-Generated by Claude
            self._project_states.values(), # AI-Generated by Claude
            key=lambda p: STATE_PRIORITY.get(p.get("state", "idle"), 0), # AI-Generated by Claude
            reverse=True, # AI-Generated by Claude
        ): # AI-Generated by Claude
            name = pdata.get("project_name", "?") # AI-Generated by Claude
            state = pdata.get("state", "idle") # AI-Generated by Claude
            emoji = STATE_EMOJI.get(state, "❓") # AI-Generated by Claude
            lines.append(f"{emoji} {name}: {state}") # AI-Generated by Claude
        self.setToolTip("\n".join(lines) if lines else "暂无活跃项目") # AI-Generated by Claude

    # ── Window motion ─────────────────────────────────────────────────────────

    @pyqtSlot(str)
    def _on_motion_changed(self, motion_type: str) -> None: # AI-Generated by Claude
        self._motion_type = motion_type # AI-Generated by Claude
        self._motion_step = 0 # AI-Generated by Claude
        if motion_type != "none": # AI-Generated by Claude
            self._motion_timer.start(50) # AI-Generated by Claude
        else: # AI-Generated by Claude
            self._motion_timer.stop() # AI-Generated by Claude
            if self._base_pos: # AI-Generated by Claude
                self.move(self._base_pos) # AI-Generated by Claude

    @pyqtSlot()
    def _apply_motion(self) -> None: # AI-Generated by Claude
        if not self._base_pos: # AI-Generated by Claude
            return # AI-Generated by Claude
        self._motion_step += 1 # AI-Generated by Claude
        bx, by = self._base_pos.x(), self._base_pos.y() # AI-Generated by Claude
        if self._motion_type == "float": # AI-Generated by Claude
            offset_y = int(3 * math.sin(self._motion_step * 0.15)) # AI-Generated by Claude
            self.move(bx, by + offset_y) # AI-Generated by Claude
        elif self._motion_type == "shake": # AI-Generated by Claude
            self.move(bx + random.randint(-2, 2), by + random.randint(-2, 2)) # AI-Generated by Claude
        elif self._motion_type == "tremble": # AI-Generated by Claude
            self.move(bx + random.randint(-1, 1), by + random.randint(-1, 1)) # AI-Generated by Claude
        if self._bubble.isVisible():  # 只在气泡可见时重定位 # AI-Generated by Claude
            self._bubble.reposition()  # AI-Generated by Claude


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None: # AI-Generated by Claude
    parser = argparse.ArgumentParser(description="Claude Desktop Pet") # AI-Generated by Claude
    parser.add_argument("--project", default=None, help="Project dir to monitor immediately") # AI-Generated by Claude
    args = parser.parse_args() # AI-Generated by Claude

    app = QApplication(sys.argv) # AI-Generated by Claude
    app.setQuitOnLastWindowClosed(False) # AI-Generated by Claude

    window = PetWindow(project=args.project) # AI-Generated by Claude
    window.show() # AI-Generated by Claude

    sys.exit(app.exec()) # AI-Generated by Claude


if __name__ == "__main__": # AI-Generated by Claude
    main() # AI-Generated by Claude
