from PyQt6.QtGui import QPainter, QColor # AI-Generated by Claude
from PyQt6.QtCore import QRect # AI-Generated by Claude


class PetRenderer: # AI-Generated by Claude
    PIXEL_SIZE = 12 # AI-Generated by Claude
    PIXEL_GAP = 1 # AI-Generated by Claude

    def __init__(self, rows: int = 6, cols: int = 8): # AI-Generated by Claude
        self._rows = rows # AI-Generated by Claude
        self._cols = cols # AI-Generated by Claude

    @property
    def rows(self) -> int: # AI-Generated by Claude
        return self._rows # AI-Generated by Claude

    @property
    def cols(self) -> int: # AI-Generated by Claude
        return self._cols # AI-Generated by Claude

    def set_dimensions(self, rows: int, cols: int) -> None: # AI-Generated by Claude
        """Dynamically set the grid dimensions.""" # AI-Generated by Claude
        self._rows = rows # AI-Generated by Claude
        self._cols = cols # AI-Generated by Claude

    def widget_width(self) -> int: # AI-Generated by Claude
        return self._cols * self.PIXEL_SIZE + (self._cols - 1) * self.PIXEL_GAP # AI-Generated by Claude

    def widget_height(self) -> int: # AI-Generated by Claude
        return self._rows * self.PIXEL_SIZE + (self._rows - 1) * self.PIXEL_GAP # AI-Generated by Claude

    def render(self, painter: QPainter, frame: list) -> None: # AI-Generated by Claude
        """Draw frame onto painter. Transparent cells are skipped."""
        step = self.PIXEL_SIZE + self.PIXEL_GAP # AI-Generated by Claude
        for row_idx, row in enumerate(frame): # AI-Generated by Claude
            y = row_idx * step # AI-Generated by Claude
            for col_idx, color in enumerate(row): # AI-Generated by Claude
                if color == "transparent": # AI-Generated by Claude
                    continue # AI-Generated by Claude
                x = col_idx * step # AI-Generated by Claude
                painter.fillRect( # AI-Generated by Claude
                    QRect(x, y, self.PIXEL_SIZE, self.PIXEL_SIZE), # AI-Generated by Claude
                    QColor(color), # AI-Generated by Claude
                )
