from PyQt6.QtGui import QPainter, QColor # AI-Generated by Claude
from PyQt6.QtCore import QRect # AI-Generated by Claude


class PetRenderer: # AI-Generated by Claude
    PIXEL_SIZE = 12 # AI-Generated by Claude
    PIXEL_GAP = 1 # AI-Generated by Claude
    COLS = 8 # AI-Generated by Claude
    ROWS = 6 # AI-Generated by Claude

    @classmethod
    def widget_width(cls) -> int: # AI-Generated by Claude
        return cls.COLS * cls.PIXEL_SIZE + (cls.COLS - 1) * cls.PIXEL_GAP # AI-Generated by Claude

    @classmethod
    def widget_height(cls) -> int: # AI-Generated by Claude
        return cls.ROWS * cls.PIXEL_SIZE + (cls.ROWS - 1) * cls.PIXEL_GAP # AI-Generated by Claude

    def render(self, painter: QPainter, frame: list) -> None: # AI-Generated by Claude
        """Draw frame onto painter. Transparent cells are skipped."""
        step = self.PIXEL_SIZE + self.PIXEL_GAP # AI-Generated by Claude
        for row_idx, row in enumerate(frame): # AI-Generated by Claude
            y = row_idx * step # AI-Generated by Claude
            for col_idx, color in enumerate(row): # AI-Generated by Claude
                if color == "transparent": # AI-Generated by Claude
                    continue # AI-Generated by Claude
                x = col_idx * step # AI-Generated by Claude
                painter.fillRect( # AI-Generated by Claude
                    QRect(x, y, self.PIXEL_SIZE, self.PIXEL_SIZE), # AI-Generated by Claude
                    QColor(color), # AI-Generated by Claude
                )
